name: 'conda builed cached'
description: 'caches conda env creation'
inputs:
  env-file:  # id of input
    description: 'name of the conda-yml file'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
      shell: bash

    - name: Restore conda package cache
      uses: actions/cache@v2
      env:
        cache-name: pkg-cache
      with:
        path: /usr/share/miniconda/pkgs
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('${{inputs.env-file}}') }}-v2

    - name: Restore build.yml cache
      uses: actions/cache@v2
      id: build-cache
      env:
        cache-name: build-cache
      with:
        path: build.yml
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('${{inputs.env-file}}') }}-v2

    - name: Install dependencies from input file
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: |
        conda env update --file ./${{inputs.env-file}} --name base
      shell: bash

    - name: Create build yml
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: conda env export --name base > build.yml
      shell: bash
      
    - name: Install dependencies from build.yml
      if: steps.build-cache.outputs.cache-hit == 'true'
      run: conda env update --file build.yml --name base
      shell: bash
