name: Build and commit documentation

on: workflow_dispatch

jobs:  
  run-test:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v2
    - uses: lukaskiwitz/thesis/conda_build_cached@v1
    - name: Set env variables
      run: | 
        conda env config vars set LD_LIBRARY_PATH=~/anaconda3/envs/base/lib
    - name: Install package
      run: pip install -e .
    - name: make html
      run: |
        cd docsrc
        make html
