name: Build and commit documentation

on: workflow_dispatch

jobs:  
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install conda env with cache
      uses: ./.github/actions/conda_build_cached/
      with:
        env-file: fenics_explicit.yml
    - name: Set env variables
      run: | 
        conda env config vars set LD_LIBRARY_PATH=~/anaconda3/envs/base/lib
    - name: Install package
      run: pip install -e .
    - name: make html
      run: |
        cd docsrc
        make html
